services:
  - type: web
    name: gymkiosk-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    autoDeploy: true
    domains:
      - app.rdpsplace.me
    envVars:
      - key: NODE_ENV
        value: production
